### PR TITLE
WEBUMENIA-920 Symfony forms in admin

### PR DESCRIPTION
**Pull request by rastislav-chynoransky**
Fixes https://jira.sng.sk/browse/WEBUMENIA-920

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

# Checklist:

- [x] I have updated the [CHANGELOG](../CHANGELOG.md)
- [ ] I have requested at least 1 reviewer for this PR
- [ ] I have made corresponding changes to the documentation

### CODE REVIEW

**Comment by rastislav-chynoransky** [comment]
@igor-kamil That's weird, it works for me. But I've force-pushed to the branch in the night, don't you have old version checked out?

**Comment by igor-kamil** [comment]
@rastislav-chynoransky no I have the current version. Now I tested it bit more - and when saving Item, it store the selected tags to all Items. it's not applied to current one but all in database everytime. 
Try it by yourself (add some tags to one item and check others)

**Comment by rastislav-chynoransky** [comment]
@igor-kamil Ok, so that's superweird. I'm maybe missing something, but it doesn't work like that for me. Do you mean when you look into db you see there all of combinations of selected tags : items?

**Comment by igor-kamil** [comment]
@rastislav-chynoransky now I see it's probably some weird problem in my own environment. I need further investigation.

**Pull request merged**
